
name: insurance-v2-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - pip
  - pip:
    - azureml-defaults
    - azureml-inference-server-http
    - joblib