name: insurance-v2-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-defaults
      - azureml-inference-server-http
      - joblib
      - pandas
      - scikit-learn
      - xgboost